### ISSUE TITLE
User can save a note.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/web-api#1]
# **Motivation** 
A note saving system so users can save notes through the terminal and have them stored in a database. 

# **Implementation**
### **Technologies**
- Mongogb for the database.
- Express.JS for the web framework.
- HTTPie for HTTP client.

### **Tasks**
- [x] Create a server using Express, have it listen on a specified port.
- [x] Get JSON body parser implemented. 
- [x] Use Express post to be invoked on the /note path.
- [x] Once invoked use Mongos insertOne() method to insert the request body.
- [x] Insert a note with HTTPie.

# **Screenshot**
![screen shot 2018-04-12 at 10 38 14 am](https://user-images.githubusercontent.com/14259747/38694126-aefb144a-3e3d-11e8-8725-7b409d37b1c2.png)
