### ISSUE TITLE
User can read a list of notes.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/web-api#2]
# **Motivation** 
A note reading system so users can read notes they have saved and have them displayed in the terminal.

# **Implementation**
### **Technologies**
- Mongogb for the database.
- Express.JS for the web framework.
- HTTPie for HTTP client.

### **Tasks**

- [x] Connect to mongo database.
- [x] Access the notes in our database library.
- [x] Use Mongo find method to return our list of notes.
- [x] Use Nodes "toArray" method to return all elements contained.
- [x] Log our results to the terminal.

# **Screenshot**
![screen shot 2018-04-12 at 10 44 18 am](https://user-images.githubusercontent.com/14259747/38694872-9ede1740-3e3f-11e8-87e9-dc2ab2a5de5b.png)
