### ISSUE TITLE
User can update a note by id.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/web-api#3]
# **Motivation** 
A note updating system so users can update notes they have saved and have them displayed in the terminal.

# **Implementation**
### **Technologies**
- Mongogb for the database.
- Express.JS for the web framework.
- HTTPie for HTTP client.

### **Tasks**

- [x] Use Express put to trigger Mongos updateOne method
- [x] Have Mongos UpdateOne method grab the requests id off the body
- [x] Have Mongos UpdateOne method grab the body of the request
- [x] Use both request ID and request body to update note indicated in HTTPies put request

# **Screenshot**
![screen shot 2018-04-12 at 2 44 31 pm](https://user-images.githubusercontent.com/14259747/38705907-1ac5568c-3e60-11e8-868a-76b410b3da42.png)
![screen shot 2018-04-12 at 2 44 41 pm](https://user-images.githubusercontent.com/14259747/38705912-1e39ca50-3e60-11e8-84e5-830cafd63200.png)
