### ISSUE TITLE
User can delete a note by id.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/web-api#4]
# **Motivation** 
A note deleting system so users can delete notes they have saved and have them removed from the terminal.

# **Implementation**
### **Technologies**
- Mongogb for the database.
- Express.JS for the web framework.
- HTTPie for HTTP client.

### **Tasks**

- [x] Use Express delete to trigger Mongos deleteOne method
- [x] Have Mongos deleteOne method grab the requests id off the body
- [x] Use request ID  to delete note indicated in HTTPies delete request

# **Screenshot**
